# -*- coding: utf-8 -*-
"""2.1.Kitap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGWxmPilPAJZupWjSwdQfN6u5xZWbsWR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras as K
from tensorflow.keras.layers import Dense

np.random.seek(0)
area=